name: Build and Deploy Node.js Application with AWS CodeDeploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"

jobs:
  build:
    name: Build and Upload Node.js Artifact
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Zip Application Code
      - name: Package Application Code
        run: zip -r artifact.zip .

      # Step 5: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::717279698366:role/github-role
          aws-region: ${{ env.AWS_REGION }}

      # Step 6: Upload Artifact to S3
      - name: Upload Artifact to S3
        run: |
          aws s3 cp artifact.zip s3://cicd-deployment-bucket/node-app/${{ github.run_id }}/artifact.zip

  deploy:
    name: Deploy Node.js App to EC2 via CodeDeploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::717279698366:role/gh-role
          aws-region: ${{ env.AWS_REGION }}

      # Step 2: Trigger CodeDeploy Deployment
      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name pdf \
            --deployment-group-name pdf \
            --s3-location bucket=cicd-deployment-bucket,bundleType=zip,key=node-app/${{ github.run_id }}/artifact.zip \
            --region ${{ env.AWS_REGION }}
